#!/usr/bin/env bash
# The Script displays the current running process with the following 
# Must show all processes, for all users, 
# including those which might not have a TTY
# Display in a user-oriented format
# Show process hierarchy

ps -a -x -u -f
