#!/usr/bin/env bash
# The Infinite loop script creates file with pid, catches signal, and removes file/exits:
# Ctrl-C (SIGINT), kill (SIGTERM), and ctrl-| (SIGQUIT)

sudo touch /var/run/myscript.pid
sudo bash -c 'echo $$ > /var/run/myscript.pid'
while true
do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "I hate the kill command"; sudo rm /var/run/myscript.pid; exit' SIGTERM
    trap 'echo "Y U no love me?!"' SIGINT
    trap 'sudo rm /var/run/myscript.pid; exit' SIGQUIT
done
